#%RAML 1.0 Library

types:
  post-customer:
    type: object
    properties:
      status:
        type: string
        example: Success
        required: false
      response:
        type: string
        example: DLC56GJKH235bkTy
        required: false