#%RAML 1.0 Library

types:
  post-customer:
    type: object
    properties:
      convenio:
        type: string
        example: '114'
      dataProtocolo:
        type: string
        example: '2023-05-23T00:00:00-03:00'
      nomeSegurado:
        type: string
        example: BETINA E RENAN TELAS LTDA
      numeroOrigem:
        type: string
        example: '20'
      numeroProposta:
        type: string
        example: '1111443'
      produto:
        type: string
        example: Porto Frota
      qtdeDiasCia:
        type: string
        example: '1'
      status:
        type: string
        example: '1'
      susep:
        type: string
        example: S5005J